steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - keycloak/Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/keycloak:$COMMIT_SHA
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/keycloak:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
